//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Valve.VR
{
    using System;
    using UnityEngine;
    
    
    public class SteamVR_Input_ActionSet_driving : Valve.VR.SteamVR_ActionSet
    {
        
        public virtual SteamVR_Action_Boolean HonkHorn
        {
            get
            {
                return SteamVR_Actions.driving_HonkHorn;
            }
        }
        
        public virtual SteamVR_Action_Single Throttle
        {
            get
            {
                return SteamVR_Actions.driving_Throttle;
            }
        }
        
        public virtual SteamVR_Action_Vibration SpeedBump
        {
            get
            {
                return SteamVR_Actions.driving_SpeedBump;
            }
        }
    }
}
