//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Valve.VR
{
    using System;
    using UnityEngine;
    
    
    public class SteamVR_Input_ActionSet_main : Valve.VR.SteamVR_ActionSet
    {
        
        public virtual SteamVR_Action_Boolean OpenInventory
        {
            get
            {
                return SteamVR_Actions.main_OpenInventory;
            }
        }
        
        public virtual SteamVR_Action_Pose RightHand
        {
            get
            {
                return SteamVR_Actions.main_RightHand;
            }
        }
        
        public virtual SteamVR_Action_Skeleton RightHand_Anim
        {
            get
            {
                return SteamVR_Actions.main_RightHand_Anim;
            }
        }
    }
}
